### ISSUE TITLE
🐛 버그 리포터 버그

### ISSUE THREAD

**Issue by ghost** [Migan178/kubot#6]
가끔씩 버그리포터 기능이 작동하지 않거나 DM이 안가는 경우도 있습니다. 기능이 불안정한것 같습니다.

**Comment by Migan178** [comment]
어떤 에러가 터미널에 발생하나요?

**Comment by Migan178** [comment]
그리고 이 버그는 아마 개발자가 오프라인(디코를 안보고 있을 때) 발생하는 것 같습니다.

**Comment by Migan178** [comment]
@ImNyang

**Comment by ghost** [comment]
네
