### ISSUE TITLE
미간넴 clear 안되는뎁숑

### ISSUE THREAD

**Issue by ghost** [Migan178/kubot#7]
<img width="1322" alt="스크린샷 2022-03-10 오전 10 55 01" src="https://user-images.githubusercontent.com/72956792/157572894-f77fe6b8-8205-4afc-a32a-b321535a4e29.png">

잘 고쳐주세요

**Comment by Migan178** [comment]
해당 문제는 14일 지난 메세지를 지울때 발생한겁니다. NAB
