### ISSUE TITLE
ID밴 작동 안됨

### ISSUE THREAD

**Issue by ghost** [Migan178/kubot#8]
<img width="386" alt="스크린샷 2022-03-16 오전 8 55 53" src="https://user-images.githubusercontent.com/72956792/158491503-a82d38e9-14c6-4401-80ef-515448a3d99d.png">

**Comment by ghost** [comment]
서버에 아예 없는 사람이라 권한이 없는것도 아닙니다.

**Comment by Migan178** [comment]
그건 ban명령어가 ID입력방식이 아니라, Mentionable (User 멘션)방식이라 어쩔수 없어요...
